sudo: required
services:
  - docker

before_install:
  - docker build -t jisu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jisu/docker-react npm run  -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker" # app name created by aws
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-306476627547" # s3 bucket
  bucket_path: "docker" # app name for the first time
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
